language: objective-c
rvm: 1.9.3
before_install:
    - brew update
    - brew upgrade xctool
    - bundle install
    - bundle exec pod install
script: 
    - xctool build -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomes -sdk iphonesimulator
    - xctool test -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomesTest -sdk iphonesimulator -freshSimulator -freshInstall ONLY_ACTIVE_ARCH=NO