language: objective-c
rvm: 1.9.3
before_install:
    - brew update
    - brew upgrade xctool
    - bundle install
    - bundle exec pod install
script: 
    - xctool -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomes -sdk iphonesimulator build -freshSimulator -freshInstall ONLY_ACTIVE_ARCH=NO
    - xctool -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomesTest -sdk iphonesimulator test -freshSimulator -freshInstall ONLY_ACTIVE_ARCH=NO