language: objective-c
rvm: 1.9.3
before_install:
    - brew update
    - brew upgrade xctool
    - gem install cocoapods -v 0.29.0 --no-ri --no-rdoc
script: 
    - xctool -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomes -sdk iphonesimulator build -freshInstall ONLY_ACTIVE_ARCH=NO
    - xctool -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomesTest -sdk iphonesimulator test -freshInstall ONLY_ACTIVE_ARCH=NO
