language: objective-c
rvm: 1.9.3
before_install:
    - brew update
    - brew upgrade xctool
    - bundle install
    - bundle exec pod install
script:
  - xctool -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomes -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomes -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO