language: objective-c
rvm: 1.9.3
before_install:
    - brew update
    - brew upgrade xctool
    - bundle install
    - bundle exec pod install
script: xctool -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomes -sdk iphonesimulator7.0 build test -freshSimulator -freshInstall ONLY_ACTIVE_ARCH=NO