language: objective-c
rvm: 1.9.3
before_install:
    - brew update
    - brew upgrade xctool --HEAD
    - gem install cocoapods -v 0.32.1 --no-ri --no-rdoc
script: 
    - xctool -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomes -sdk iphonesimulator clean build
    - xctool -workspace LesTaxinomes.xcworkspace -scheme LesTaxinomesTests -sdk iphonesimulator -destination platform='iOS Simulator',OS=7.0,name='iPhone Retina (4-inch)' -resetSimulator ONLY_ACTIVE_ARCH=NO clean test