xcodeproj 'LesTaxinomes/LesTaxinomes.xcodeproj'

pod 'AFNetworking',             '~> 1.3'
pod 'MWPhotoBrowser',           '~> 1.2'
pod 'MagicalRecord',            '~> 2.1'
pod 'SVProgressHUD',            '~> 0.9'
pod 'Reachability',             '~> 3.1'
pod 'UIKitCategoryAdditions', 	'~> 0.0'
pod 'xmlrpc',                   '~> 2.3'
pod 'AGMedallionView',          '~> 1.1'
pod 'PonyDebugger',             '~> 0.3'
